import type { Metadata } from "next";
import "./globals.css";



export const metadata: Metadata = {
  title: "IBLOCKPAD",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-graphik-arabic font-medium">{children}</body>
    </html>
  );
}
